# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        my_config_1:
            toolbar: "my_toolbar_1"

    toolbars:
        configs:
            my_toolbar_1: [ 
                [ 
                    "Undo", "Redo", 
                    "-", 
                    "Bold", 
                    "Italic",
                    "Underline",
                    "Strike", 
                    "-",
                    "Subscript",
                    "Superscript", 
                    "-",
                    "JustifyLeft",
                    "JustifyCenter",
                    "JustifyRight",
                    "JustifyBlock",
                    "-",
                    "Format",
                    "-",
                    "Font", 
                    "FontSize", 
                    "TextColor", 
                    "BGColor", 
                    "-", 
                    "Link", "-",
                    "BulletedList", "-",
                    "NumberedList", "-",
                    "Outdent", "-", 
                    "Indent", "-", 
                    "Find", 
                ]
            ]
            